package com.tsmc.lims.backend.shared.service;

import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

@Service
public class EmailService {

    private final JavaMailSender mailSender;

    public EmailService(JavaMailSender mailSender) {
        this.mailSender = mailSender;
    }

    /**
     * Sends a branded LIMS TOTP verification email.
     * Used for both registration (AuthService) and password change (ProfileService).
     */
    public void sendTotpEmail(String toAddress, String subject, String bodyHeading, String bodyDesc, String code) {
        try {
            MimeMessage mimeMessage = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(mimeMessage, true, "UTF-8");
            helper.setTo(toAddress);
            helper.setSubject(subject);
            helper.setText(buildHtml(bodyHeading, bodyDesc, code), true);
            mailSender.send(mimeMessage);
        } catch (MessagingException e) {
            throw new RuntimeException("CRITICAL: Failed to send TOTP email to " + toAddress, e);
        }
    }

    // Shared HTML template ¡X single source of truth for all LIMS verification emails
    private String buildHtml(String heading, String desc, String code) {
        return """
            <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #f8fafc; padding: 40px 20px; margin: 0;">
                <div style="max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1);">
                    <div style="background-color: #0f172a; padding: 24px; text-align: center;">
                        <h2 style="color: #ffffff; margin: 0; font-size: 24px; letter-spacing: 2px; text-transform: uppercase;">LIMS Portal</h2>
                    </div>
                    <div style="padding: 32px; color: #334155;">
                        <h3 style="margin-top: 0; color: #0f172a; font-size: 20px;">%s</h3>
                        <p style="font-size: 16px; line-height: 1.6;">Hello,</p>
                        <p style="font-size: 16px; line-height: 1.6;">%s</p>
                        <div style="text-align: center; margin: 36px 0;">
                            <span style="display: inline-block; font-size: 36px; font-weight: bold; color: #2563eb; background-color: #f1f5f9; padding: 16px 32px; border-radius: 8px; letter-spacing: 12px; border: 1px solid #e2e8f0;">%s</span>
                        </div>
                        <p style="font-size: 14px; color: #64748b; line-height: 1.6; padding: 12px; background-color: #fffbeb; border-left: 4px solid #f59e0b; border-radius: 4px;">
                            <strong>Security Alert:</strong> This code will expire shortly. Do not share this code with anyone. The IT department will never ask for your verification code.
                        </p>
                    </div>
                    <div style="background-color: #f8fafc; border-top: 1px solid #e2e8f0; padding: 24px; text-align: center;">
                        <p style="font-size: 12px; color: #94a3b8; margin: 0;">This is an automated message generated by the TSMC LIMS system.</p>
                        <p style="font-size: 12px; color: #94a3b8; margin: 4px 0 0 0;">Please do not reply to this email.</p>
                    </div>
                </div>
            </div>
            """.formatted(heading, desc, code);
    }
}